In [1]:
import pandas as pd 
import numpy as np

In [2]:
nba=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/nba.csv")

In [3]:
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
nba.dropna() # drops all the missing rows

In [4]:
nba.dropna(how="all") # to drop a line of Na Value 
nba.dropna(subset=["College"])

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0

In [5]:
nba["Salary"]=nba["Salary"].fillna(0)

In [6]:
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,0.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [7]:
nba['College']=nba['College'].fillna('Unknown')

In [8]:
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,0.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,Unknown,0.0

In [13]:
nba.loc[:,['Name','Team','Position']].head()

                Name           Team Position
0         Saddiq Bey  Atlanta Hawks        F
1  Bogdan Bogdanovic  Atlanta Hawks        G
2        Kobe Bufkin  Atlanta Hawks        G
3       Clint Capela  Atlanta Hawks        C
4     Bruno Fernando  Atlanta Hawks      F-C

In [15]:
nba.loc[nba['Position']=='G',['Name','Team','Position']]

                  Name                Team Position
1    Bogdan Bogdanovic       Atlanta Hawks        G
2          Kobe Bufkin       Atlanta Hawks        G
5        Trent Forrest       Atlanta Hawks        G
10          Seth Lundy       Atlanta Hawks        G
11    Garrison Mathews       Atlanta Hawks        G
..                 ...                 ...      ...
584      Kendrick Nunn  Washington Wizards        G
586       Jordan Poole  Washington Wizards        G
587       Ryan Rollins  Washington Wizards        G
588      Landry Shamet  Washington Wizards        G
590       Delon Wright  Washington Wizards        G

[229 rows x 3 columns]

In [17]:
nba['Salary_Increase']=nba['Salary']*1.05 # broadcast

In [18]:
nba

,Name,Team,Position,Height,Weight,College,Salary,Salary_Increase
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0,4784832.15
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0,19635000.00
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0,4298956.20
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0,21646800.00
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0,2710598.10
...,...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0,1805857.20
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0,10762500.00
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,0.0,0.00
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0,8604878.10
591,NaN,NaN,NaN,NaN,NaN,Unknown,0.0,0.00

In [24]:
data={'Name':['Madhan','Megha','','Vishak','Ahill'],
      'Class':['SBA','BTECH','MT','','FIB'],
      'Roll':[35,2,10,41,'']}
df=pd.DataFrame(data)
df

     Name  Class Roll
0  Madhan    SBA   35
1   Megha  BTECH    2
2             MT   10
3  Vishak          41
4   Ahill    FIB

In [25]:
nba.iloc[:10,3] #:after is rows and after, is the columns

0     6-7
1     6-5
2     6-5
3    6-10
4    6-10
5     6-4
6     6-6
7    6-11
8     6-8
9     6-8
Name: Height, dtype: object