In [1]:
import pandas as pd 
import numpy as np

In [2]:
nba=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/nba.csv")

In [3]:
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
nba["Extra"]=nba["Weight"] #adding extra columns with value

In [41]:
nba

,Name,Team,Position,Height,Weight,College,Salary,Extra
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0,215.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0,225.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0,195.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0,256.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0,240.0
...,...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0,180.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0,190.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN,220.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0,185.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
nba["Madhan"]= "" # to add extra column with blank space

In [43]:
nba

,Name,Team,Position,Height,Weight,College,Salary,Extra,Madhan
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0,215.0,
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0,225.0,
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0,195.0,
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0,256.0,
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0,240.0,
...,...,...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0,180.0,
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0,190.0,
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN,220.0,
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0,185.0,
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [44]:
nba["Salary increase"]= 0.05
nba["Salary revised"]= nba["Salary"]+nba["Salary"]*0.05

In [45]:
nba

,Name,Team,Position,Height,Weight,College,Salary,Extra,Madhan,Salary increase,Salary revised
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0,215.0,,0.05,4784832.15
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0,225.0,,0.05,19635000.00
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0,195.0,,0.05,4298956.20
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0,256.0,,0.05,21646800.00
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0,240.0,,0.05,2710598.10
...,...,...,...,...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0,180.0,,0.05,1805857.20
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0,190.0,,0.05,10762500.00
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN,220.0,,0.05,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0,185.0,,0.05,8604878.10
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0.05,NaN

In [46]:
#replacing Na values in college column with "unknown "

In [47]:
nba["College"]= nba["College"].replace(np.nan,"Unknown")

In [48]:
nba["College"]

0          Villanova
1         Fenerbahce
2           Michigan
3        Elan Chalon
4           Maryland
           ...
587           Toledo
588    Wichita State
589      Real Madrid
590             Utah
591          Unknown
Name: College, Length: 592, dtype: object

In [49]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 592 entries, 0 to 591
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             591 non-null    object
 1   Team             591 non-null    object
 2   Position         584 non-null    object
 3   Height           585 non-null    object
 4   Weight           584 non-null    float64
 5   College          592 non-null    object
 6   Salary           488 non-null    float64
 7   Extra            584 non-null    float64
 8   Madhan           592 non-null    object
 9   Salary increase  592 non-null    float64
 10  Salary revised   488 non-null    float64
dtypes: float64(5), object(6)
memory usage: 51.0+ KB

In [ ]:
nba[("Salary" >