In [1]:
import pandas as pd 
import numpy as np

In [2]:
google=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/google_stock_price.csv")

In [3]:
google

            Date       Price
0     2004-08-19    2.490664
1     2004-08-20    2.515820
2     2004-08-23    2.758411
3     2004-08-24    2.770615
4     2004-08-25    2.614201
...          ...         ...
4788  2023-08-28  132.080002
4789  2023-08-29  132.998001
4790  2023-08-30  135.570007
4791  2023-08-31  137.050003
4792  2023-09-01  138.429993

[4793 rows x 2 columns]

In [4]:
google=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/google_stock_price.csv",usecols=["Price"])

In [5]:
google

           Price
0       2.490664
1       2.515820
2       2.758411
3       2.770615
4       2.614201
...          ...
4788  132.080002
4789  132.998001
4790  135.570007
4791  137.050003
4792  138.429993

[4793 rows x 1 columns]

In [6]:
google=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/google_stock_price.csv",usecols=["Price"]).squeeze("columns")

In [7]:
google

0         2.490664
1         2.515820
2         2.758411
3         2.770615
4         2.614201
           ...
4788    132.080002
4789    132.998001
4790    135.570007
4791    137.050003
4792    138.429993
Name: Price, Length: 4793, dtype: float64

In [8]:
google.head(25)

0     2.490664
1     2.515820
2     2.758411
3     2.770615
4     2.614201
5     2.613952
6     2.692408
7     2.622171
8     2.547950
9     2.557912
10    2.470490
11    2.514326
12    2.515820
13    2.509095
14    2.553678
15    2.530515
16    2.655795
17    2.676219
18    2.753679
19    2.798012
20    2.849818
21    2.912832
22    2.984065
23    2.924040
24    2.959906
Name: Price, dtype: float64

In [13]:
google.describe()

count    4793.000000
mean       40.211377
std        37.274753
min         2.470490
25%        12.767395
50%        26.327717
75%        56.311001
max       151.863495
Name: Price, dtype: float64

In [14]:
google.info()

<class 'pandas.core.series.Series'>
RangeIndex: 4793 entries, 0 to 4792
Series name: Price
Non-Null Count  Dtype
--------------  -----
4793 non-null   float64
dtypes: float64(1)
memory usage: 37.6 KB

In [15]:
google.shape

(4793,)

In [9]:
google.tail(25)

4768    133.009995
4769    130.854996
4770    129.839996
4771    128.369995
4772    129.600006
4773    129.509995
4774    130.979996
4775    132.190002
4776    131.970001
4777    129.201996
4778    129.850006
4779    131.589996
4780    129.279999
4781    130.449997
4782    129.059998
4783    127.849998
4784    129.130005
4785    130.850006
4786    134.727005
4787    130.139999
4788    132.080002
4789    132.998001
4790    135.570007
4791    137.050003
4792    138.429993
Name: Price, dtype: float64

In [10]:
min(google)

2.47049