In [1]:
import pandas as pd 
import numpy as np

In [2]:
food=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/restaurant_foods.csv")
w1=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/restaurant_week_1_sales.csv")
w2=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/restaurant_week_2_sales.csv")
customers=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/restaurant_customers.csv")

In [3]:
food

   Food ID   Food Item  Price
0        1       Sushi   3.99
1        2     Burrito   9.99
2        3        Taco   2.99
3        4  Quesadilla   4.25
4        5       Pizza   2.49
5        6       Pasta  13.99
6        7       Steak  24.99
7        8       Salad  11.25
8        9       Donut   0.99
9       10       Drink   1.75

In [4]:
w1.head()

   Customer ID  Food ID
0          537        9
1           97        4
2          658        1
3          202        2
4          155        9

In [5]:
w2.head()

   Customer ID  Food ID
0          688       10
1          813        7
2          495       10
3          189        5
4          267        3

In [6]:
len(w1)

250

In [7]:
len(w2)

250

In [8]:
pd.concat([w1,w2])

     Customer ID  Food ID
0            537        9
1             97        4
2            658        1
3            202        2
4            155        9
..           ...      ...
245          783       10
246          556       10
247          547        9
248          252        9
249          249        6

[500 rows x 2 columns]

In [9]:
pd.concat([w1,w2],ignore_index=False)

     Customer ID  Food ID
0            537        9
1             97        4
2            658        1
3            202        2
4            155        9
..           ...      ...
245          783       10
246          556       10
247          547        9
248          252        9
249          249        6

[500 rows x 2 columns]

In [10]:
pd.concat([w1,w2],ignore_index=True)

     Customer ID  Food ID
0            537        9
1             97        4
2            658        1
3            202        2
4            155        9
..           ...      ...
495          783       10
496          556       10
497          547        9
498          252        9
499          249        6

[500 rows x 2 columns]

In [11]:
pd.concat([w1,w2],keys=['Week 1','Week 2']).sort_index()

            Customer ID  Food ID
Week 1 0            537        9
       1             97        4
       2            658        1
       3            202        2
       4            155        9
...                 ...      ...
Week 2 245          783       10
       246          556       10
       247          547        9
       248          252        9
       249          249        6

[500 rows x 2 columns]

In [12]:
df1 =pd.DataFrame([1,2,3],columns=['A'])
df1

   A
0  1
1  2
2  3

In [13]:
df2=pd.DataFrame([4,5,6],columns=['B'])
df2

   B
0  4
1  5
2  6

In [14]:
pd.concat([df1,df2])

     A    B
0  1.0  NaN
1  2.0  NaN
2  3.0  NaN
0  NaN  4.0
1  NaN  5.0
2  NaN  6.0

In [15]:
pd.concat([df1,df2],axis="index")

     A    B
0  1.0  NaN
1  2.0  NaN
2  3.0  NaN
0  NaN  4.0
1  NaN  5.0
2  NaN  6.0

In [16]:
pd.concat([df1,df2],axis="columns")

   A  B
0  1  4
1  2  5
2  3  6

# left joint

In [17]:
food=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/restaurant_foods.csv")
w1=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/restaurant_week_1_sales.csv")
w2=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/restaurant_week_2_sales.csv")
customers=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/restaurant_customers.csv")
w1.head()

   Customer ID  Food ID
0          537        9
1           97        4
2          658        1
3          202        2
4          155        9

In [18]:
food.head()

   Food ID   Food Item  Price
0        1       Sushi   3.99
1        2     Burrito   9.99
2        3        Taco   2.99
3        4  Quesadilla   4.25
4        5       Pizza   2.49

In [19]:
w1.merge(food,how='left',on='Food ID')

     Customer ID  Food ID   Food Item  Price
0            537        9       Donut   0.99
1             97        4  Quesadilla   4.25
2            658        1       Sushi   3.99
3            202        2     Burrito   9.99
4            155        9       Donut   0.99
..           ...      ...         ...    ...
245          413        9       Donut   0.99
246          926        6       Pasta  13.99
247          134        3        Taco   2.99
248          396        6       Pasta  13.99
249          535       10       Drink   1.75

[250 rows x 4 columns]

In [20]:
w2.head()

   Customer ID  Food ID
0          688       10
1          813        7
2          495       10
3          189        5
4          267        3

In [21]:
customers.head()

   ID First Name Last Name  Gender  Company                     Occupation
0   1     Joseph   Perkins    Male  Dynazzy  Community Outreach Specialist
1   2   Jennifer   Alvarez  Female     DabZ        Senior Quality Engineer
2   3      Roger     Black    Male  Tagfeed              Account Executive
3   4     Steven     Evans    Male     Fatz               Registered Nurse
4   5       Judy  Morrison  Female  Demivee                Legal Assistant

In [22]:
w2.merge(customers,how='left',left_on='Customer ID',right_on='ID')

,Customer ID,Food ID,ID,First Name,Last Name,Gender,Company,Occupation
0,688,10,688,Carl,Williamson,Male,Thoughtmix,Graphic Designer
1,813,7,813,Johnny,Walker,Male,Kayveo,Developer II
2,495,10,495,Deborah,Little,Female,Babbleblab,VP Accounting
3,189,5,189,Roger,Gordon,Male,Skilith,Operator
4,267,3,267,Matthew,Wood,Male,Agimba,Product Engineer
...,...,...,...,...,...,...,...,...
245,783,10,783,Phyllis,Meyer,Female,Voolia,Information Systems Manager
246,556,10,556,Samuel,Bailey,Male,Oyoloo,Nurse
247,547,9,547,Tina,Watkins,Female,Thoughtstorm,Accountant II
248,252,9,252,Douglas,Powell,Male,Jetwire,Geologist IV
249,249,6,249,Anthony,Carpenter,Male,Shuffletag,Health Coach I

In [23]:
w2.merge(customers,how='left',left_on='Customer ID',right_on='ID').drop('ID',axis='columns')

,Customer ID,Food ID,First Name,Last Name,Gender,Company,Occupation
0,688,10,Carl,Williamson,Male,Thoughtmix,Graphic Designer
1,813,7,Johnny,Walker,Male,Kayveo,Developer II
2,495,10,Deborah,Little,Female,Babbleblab,VP Accounting
3,189,5,Roger,Gordon,Male,Skilith,Operator
4,267,3,Matthew,Wood,Male,Agimba,Product Engineer
...,...,...,...,...,...,...,...
245,783,10,Phyllis,Meyer,Female,Voolia,Information Systems Manager
246,556,10,Samuel,Bailey,Male,Oyoloo,Nurse
247,547,9,Tina,Watkins,Female,Thoughtstorm,Accountant II
248,252,9,Douglas,Powell,Male,Jetwire,Geologist IV
249,249,6,Anthony,Carpenter,Male,Shuffletag,Health Coach I

# Inner Join

In [24]:
food=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/restaurant_foods.csv")
w1=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/restaurant_week_1_sales.csv")
w2=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/restaurant_week_2_sales.csv")
customers=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/restaurant_customers.csv")

In [25]:
w1

     Customer ID  Food ID
0            537        9
1             97        4
2            658        1
3            202        2
4            155        9
..           ...      ...
245          413        9
246          926        6
247          134        3
248          396        6
249          535       10

[250 rows x 2 columns]

In [26]:
w1[w1['Customer ID']==155]

    Customer ID  Food ID
4           155        9
17          155        1

In [27]:
w2[w2['Customer ID']==155]

     Customer ID  Food ID
208          155        3

In [28]:
w1.merge(w2,how='inner',on='Customer ID')

    Customer ID  Food ID_x  Food ID_y
0           537          9          5
1           155          9          3
2           503          5          8
3           503          5          9
4           155          1          3
..          ...        ...        ...
57          945          5          4
58          343          3          5
59          343          3          2
60          343          3          7
61          621          9          6

[62 rows x 3 columns]

In [29]:
w1.merge(w2,how='inner',on='Customer ID',suffixes=[' - Week1',' - Week2'])

    Customer ID  Food ID - Week1  Food ID - Week2
0           537                9                5
1           155                9                3
2           503                5                8
3           503                5                9
4           155                1                3
..          ...              ...              ...
57          945                5                4
58          343                3                5
59          343                3                2
60          343                3                7
61          621                9                6

[62 rows x 3 columns]

# inner joins II

In [30]:
food=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/restaurant_foods.csv")
w1=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/restaurant_week_1_sales.csv")
w2=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/restaurant_week_2_sales.csv")
customers=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/restaurant_customers.csv")

In [31]:
w1.head()

   Customer ID  Food ID
0          537        9
1           97        4
2          658        1
3          202        2
4          155        9

In [32]:
w1.merge(w2,how='inner',on=['Customer ID','Food ID'])

   Customer ID  Food ID
0          304        3
1          540        3
2          937       10
3          233        3
4           21        4
5          922        1
6           21        4
7          578        5
8          578        5

In [33]:
condition_one = w1['Customer ID']==578
condition_two = w1['Food ID']==5
w1[condition_one]

     Customer ID  Food ID
224          578        5

# Full/Outer Join

In [35]:
food=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/restaurant_foods.csv")
w1=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/restaurant_week_1_sales.csv")
w2=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/restaurant_week_2_sales.csv")
customers=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/restaurant_customers.csv")

In [36]:
w1.head()

   Customer ID  Food ID
0          537        9
1           97        4
2          658        1
3          202        2
4          155        9

In [38]:
w1.merge(w2,how="outer",on="Customer ID")

     Customer ID  Food ID_x  Food ID_y
0              3        2.0        NaN
1              8        NaN        6.0
2             10        2.0        NaN
3             13        NaN        2.0
4             20        1.0        NaN
..           ...        ...        ...
449          985        5.0        NaN
450          991        2.0        NaN
451          994        NaN        2.0
452          996        NaN       10.0
453         1000        2.0        NaN

[454 rows x 3 columns]

In [39]:
w1.merge(w2,how="outer",on="Customer ID",suffixes=[" - Week 1"," - Week 2"])

     Customer ID  Food ID - Week 1  Food ID - Week 2
0              3               2.0               NaN
1              8               NaN               6.0
2             10               2.0               NaN
3             13               NaN               2.0
4             20               1.0               NaN
..           ...               ...               ...
449          985               5.0               NaN
450          991               2.0               NaN
451          994               NaN               2.0
452          996               NaN              10.0
453         1000               2.0               NaN

[454 rows x 3 columns]

In [40]:
w1.merge(w2,how="outer",on="Customer ID",suffixes=[" - Week 1"," - Week 2"],indicator=True)

     Customer ID  Food ID - Week 1  Food ID - Week 2      _merge
0              3               2.0               NaN   left_only
1              8               NaN               6.0  right_only
2             10               2.0               NaN   left_only
3             13               NaN               2.0  right_only
4             20               1.0               NaN   left_only
..           ...               ...               ...         ...
449          985               5.0               NaN   left_only
450          991               2.0               NaN   left_only
451          994               NaN               2.0  right_only
452          996               NaN              10.0  right_only
453         1000               2.0               NaN   left_only

[454 rows x 4 columns]

In [46]:
merged =w1.merge(w2,how="outer",on="Customer ID",suffixes=[" - Week 1"," - Week 2"],indicator=True)

In [47]:
merged["_merge"].value_counts()

_merge
right_only    197
left_only     195
both           62
Name: count, dtype: int64

In [49]:
merged[merged["_merge"].isin(["left_only","right_only"])]

     Customer ID  Food ID - Week 1  Food ID - Week 2      _merge
0              3               2.0               NaN   left_only
1              8               NaN               6.0  right_only
2             10               2.0               NaN   left_only
3             13               NaN               2.0  right_only
4             20               1.0               NaN   left_only
..           ...               ...               ...         ...
449          985               5.0               NaN   left_only
450          991               2.0               NaN   left_only
451          994               NaN               2.0  right_only
452          996               NaN              10.0  right_only
453         1000               2.0               NaN   left_only

[392 rows x 4 columns]

# merging by indexes with the left_index and right_index parameters

In [53]:
food=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/restaurant_foods.csv",index_col="Food ID")
w1=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/restaurant_week_1_sales.csv")
w2=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/restaurant_week_2_sales.csv")
customers=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/restaurant_customers.csv",index_col="ID")

In [54]:
food.head()

          Food Item  Price
Food ID
1             Sushi   3.99
2           Burrito   9.99
3              Taco   2.99
4        Quesadilla   4.25
5             Pizza   2.49

In [55]:
customers.head()

   First Name Last Name  Gender  Company                     Occupation
ID
1      Joseph   Perkins    Male  Dynazzy  Community Outreach Specialist
2    Jennifer   Alvarez  Female     DabZ        Senior Quality Engineer
3       Roger     Black    Male  Tagfeed              Account Executive
4      Steven     Evans    Male     Fatz               Registered Nurse
5        Judy  Morrison  Female  Demivee                Legal Assistant

In [57]:
w1.merge(
    customers,how="left",left_on="Customer ID",right_index=True
).merge(food,how="left",left_on="Food ID",right_index=True)

,Customer ID,Food ID,First Name,Last Name,Gender,Company,Occupation,Food Item,Price
0,537,9,Cheryl,Carroll,Female,Zoombeat,Registered Nurse,Donut,0.99
1,97,4,Amanda,Watkins,Female,Ozu,Account Coordinator,Quesadilla,4.25
2,658,1,Patrick,Webb,Male,Browsebug,Community Outreach Specialist,Sushi,3.99
3,202,2,Louis,Campbell,Male,Rhynoodle,Account Representative III,Burrito,9.99
4,155,9,Carolyn,Diaz,Female,Gigazoom,Database Administrator III,Donut,0.99
...,...,...,...,...,...,...,...,...,...
245,413,9,Diane,Bailey,Female,Wikibox,Technical Writer,Donut,0.99
246,926,6,Anne,Wagner,Female,Skyba,Legal Assistant,Pasta,13.99
247,134,3,Diana,Hall,Female,Quinu,Financial Advisor,Taco,2.99
248,396,6,Juan,Romero,Male,Zoonder,Analyst Programmer,Pasta,13.99
249,535,10,Nancy,Cox,Female,Trudeo,Research Associate,Drink,1.75