In [1]:
import pandas as pd 
import numpy as np

In [2]:
nba=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/nba.csv")
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
nba=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/nba.csv",usecols=["College"]).squeeze("columns")
nba

0          Villanova
1         Fenerbahce
2           Michigan
3        Elan Chalon
4           Maryland
           ...
587           Toledo
588    Wichita State
589      Real Madrid
590             Utah
591              NaN
Name: College, Length: 592, dtype: object

In [4]:
nba=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/nba.csv")

In [5]:
nba.sort_index(ascending=False)

,Name,Team,Position,Height,Weight,College,Salary
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
...,...,...,...,...,...,...,...
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0

In [6]:
nba.sort_values(by="Name")

,Name,Team,Position,Height,Weight,College,Salary
122,A.J. Lawson,Dallas Mavericks,G,6-6,179.0,South Carolina,NaN
324,AJ Green,Milwaukee Bucks,G,6-5,190.0,Northern Iowa,1901769.0
6,AJ Griffin,Atlanta Hawks,F,6-6,220.0,Duke,3712920.0
141,Aaron Gordon,Denver Nuggets,F,6-8,235.0,Arizona,22266182.0
198,Aaron Holiday,Houston Rockets,G,6-0,185.0,UCLA,2346614.0
...,...,...,...,...,...,...,...
83,Zach LaVine,Chicago Bulls,G,6-5,200.0,UCLA,40064220.0
149,Zeke Nnaji,Denver Nuggets,F-C,6-9,240.0,Arizona,4306281.0
291,Ziaire Williams,Memphis Grizzlies,F,6-9,185.0,Stanford,4810200.0
370,Zion Williamson,New Orleans Pelicans,F,6-6,284.0,Duke,34005250.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
nba.sort_values("Name",ascending=False)

,Name,Team,Position,Height,Weight,College,Salary
370,Zion Williamson,New Orleans Pelicans,F,6-6,284.0,Duke,34005250.0
291,Ziaire Williams,Memphis Grizzlies,F,6-9,185.0,Stanford,4810200.0
149,Zeke Nnaji,Denver Nuggets,F-C,6-9,240.0,Arizona,4306281.0
83,Zach LaVine,Chicago Bulls,G,6-5,200.0,UCLA,40064220.0
515,Zach Collins,San Antonio Spurs,F-C,6-11,250.0,Gonzaga,7700000.0
...,...,...,...,...,...,...,...
141,Aaron Gordon,Denver Nuggets,F,6-8,235.0,Arizona,22266182.0
6,AJ Griffin,Atlanta Hawks,F,6-6,220.0,Duke,3712920.0
324,AJ Green,Milwaukee Bucks,G,6-5,190.0,Northern Iowa,1901769.0
122,A.J. Lawson,Dallas Mavericks,G,6-6,179.0,South Carolina,NaN
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
nba=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/nba.csv")
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
nba[["Feet","Inch"]]=nba["Height"].str.split("-",expand=True)

In [11]:
nba

,Name,Team,Position,Height,Weight,College,Salary,Feet,Inch
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0,6,7
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0,6,5
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0,6,5
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0,6,10
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0,6,10
...,...,...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0,6,3
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0,6,4
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN,6,10
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0,6,5
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 592 entries, 0 to 591
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      591 non-null    object
 1   Team      591 non-null    object
 2   Position  584 non-null    object
 3   Height    585 non-null    object
 4   Weight    584 non-null    float64
 5   College   578 non-null    object
 6   Salary    488 non-null    float64
 7   Feet      585 non-null    object
 8   Inch      585 non-null    object
dtypes: float64(2), object(7)
memory usage: 41.8+ KB

In [15]:
nba[["Feet","Inch"]]=nba[["Feet","Inch"]].apply(pd.to_numeric)

In [16]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 592 entries, 0 to 591
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      591 non-null    object
 1   Team      591 non-null    object
 2   Position  584 non-null    object
 3   Height    585 non-null    object
 4   Weight    584 non-null    float64
 5   College   578 non-null    object
 6   Salary    488 non-null    float64
 7   Feet      585 non-null    float64
 8   Inch      585 non-null    float64
dtypes: float64(4), object(5)
memory usage: 41.8+ KB

In [17]:
nba["Feet"]*30.48+nba["Inch"]*2.54

0      200.66
1      195.58
2      195.58
3      208.28
4      208.28
        ...
587    190.50
588    193.04
589    208.28
590    195.58
591       NaN
Length: 592, dtype: float64

In [19]:
nba['centimeters']= nba["Feet"]*30.48+nba["Inch"]*2.54

In [20]:
nba

,Name,Team,Position,Height,Weight,College,Salary,Feet,Inch,centimeters
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0,6.0,7.0,200.66
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0,6.0,5.0,195.58
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0,6.0,5.0,195.58
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0,6.0,10.0,208.28
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0,6.0,10.0,208.28
...,...,...,...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0,6.0,3.0,190.50
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0,6.0,4.0,193.04
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN,6.0,10.0,208.28
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0,6.0,5.0,195.58
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
nba.drop("centimeters",axis=1,inplace=True)

In [23]:
nba

,Name,Team,Position,Height,Weight,College,Salary,Feet,Inch
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0,6.0,7.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0,6.0,5.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0,6.0,5.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0,6.0,10.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0,6.0,10.0
...,...,...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0,6.0,3.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0,6.0,4.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN,6.0,10.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0,6.0,5.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN