In [1]:
import pandas as pd 
import numpy as np

In [2]:
pokemon=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/pokemon.csv")

In [3]:
pokemon

              Name              Type
0        Bulbasaur     Grass, Poison
1          Ivysaur     Grass, Poison
2         Venusaur     Grass, Poison
3       Charmander              Fire
4       Charmeleon              Fire
...            ...               ...
1005  Iron Valiant   Fairy, Fighting
1006      Koraidon  Fighting, Dragon
1007      Miraidon  Electric, Dragon
1008  Walking Wake     Water, Dragon
1009   Iron Leaves    Grass, Psychic

[1010 rows x 2 columns]

In [4]:
pokemon=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/pokemon.csv",usecols=["Name"])

In [5]:
pokemon

              Name
0        Bulbasaur
1          Ivysaur
2         Venusaur
3       Charmander
4       Charmeleon
...            ...
1005  Iron Valiant
1006      Koraidon
1007      Miraidon
1008  Walking Wake
1009   Iron Leaves

[1010 rows x 1 columns]

In [6]:
pokemon=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/pokemon.csv",usecols=["Name"]).squeeze("columns")

In [7]:
pokemon

0          Bulbasaur
1            Ivysaur
2           Venusaur
3         Charmander
4         Charmeleon
            ...
1005    Iron Valiant
1006        Koraidon
1007        Miraidon
1008    Walking Wake
1009     Iron Leaves
Name: Name, Length: 1010, dtype: object

In [8]:
len(pokemon)

1010

In [9]:
list(pokemon)

['Bulbasaur',
 'Ivysaur',
 'Venusaur',
 'Charmander',
 'Charmeleon',
 'Charizard',
 'Squirtle',
 'Wartortle',
 'Blastoise',
 'Caterpie',
 'Metapod',
 'Butterfree',
 'Weedle',
 'Kakuna',
 'Beedrill',
 'Pidgey',
 'Pidgeotto',
 'Pidgeot',
 'Rattata',
 'Raticate',
 'Spearow',
 'Fearow',
 'Ekans',
 'Arbok',
 'Pikachu',
 'Raichu',
 'Sandshrew',
 'Sandslash',
 'Nidoran♀',
 'Nidorina',
 'Nidoqueen',
 'Nidoran♂',
 'Nidorino',
 'Nidoking',
 'Clefairy',
 'Clefable',
 'Vulpix',
 'Ninetales',
 'Jigglypuff',
 'Wigglytuff',
 'Zubat',
 'Golbat',
 'Oddish',
 'Gloom',
 'Vileplume',
 'Paras',
 'Parasect',
 'Venonat',
 'Venomoth',
 'Diglett',
 'Dugtrio',
 'Meowth',
 'Persian',
 'Psyduck',
 'Golduck',
 'Mankey',
 'Primeape',
 'Growlithe',
 'Arcanine',
 'Poliwag',
 'Poliwhirl',
 'Poliwrath',
 'Abra',
 'Kadabra',
 'Alakazam',
 'Machop',
 'Machoke',
 'Machamp',
 'Bellsprout',
 'Weepinbell',
 'Victreebel',
 'Tentacool',
 'Tentacruel',
 'Geodude',
 'Graveler',
 'Golem',
 'Ponyta',
 'Rapidash',
 'Slowpoke',
 'Slowbro',
 'Magnemite',
 'Magneton',
 'Farfetch’d',
 'Doduo',
 'Dodrio',
 'Seel',
 'Dewgong',
 'Grimer',
 'Muk',
 'Shellder',
 'Cloyster',
 'Gastly',
 'Haunter',
 'Gengar',
 'Onix',
 'Drowzee',
 'Hypno',
 'Krabby',
 'Kingler',
 'Voltorb',
 'Electrode',
 'Exeggcute',
 'Exeggutor',
 'Cubone',
 'Marowak',
 'Hitmonlee',
 'Hitmonchan',
 'Lickitung',
 'Koffing',
 'Weezing',
 'Rhyhorn',
 'Rhydon',
 'Chansey',
 'Tangela',
 'Kangaskhan',
 'Horsea',
 'Seadra',
 'Goldeen',
 'Seaking',
 'Staryu',
 'Starmie',
 'Mr. Mime',
 'Scyther',
 'Jynx',
 'Electabuzz',
 'Magmar',
 'Pinsir',
 'Tauros',
 'Magikarp',
 'Gyarados',
 'Lapras',
 'Ditto',
 'Eevee',
 'Vaporeon',
 'Jolteon',
 'Flareon',
 'Porygon',
 'Omanyte',
 'Omastar',
 'Kabuto',
 'Kabutops',
 'Aerodactyl',
 'Snorlax',
 'Articuno',
 'Zapdos',
 'Moltres',
 'Dratini',
 'Dragonair',
 'Dragonite',
 'Mewtwo',
 'Mew',
 'Chikorita',
 'Bayleef',
 'Meganium',
 'Cyndaquil',
 'Quilava',
 'Typhlosion',
 'Totodile',
 'Croconaw',
 'Feraligatr',
 'Sentret',
 'Furret',
 'Hoothoot',
 'Noctowl',
 'Ledyba',
 'Ledian',
 'Spinarak',
 'Ariados',
 'Crobat',
 'Chinchou',
 'Lanturn',
 'Pichu',
 'Cleffa',
 'Igglybuff',
 'Togepi',
 'Togetic',
 'Natu',
 'Xatu',
 'Mareep',
 'Flaaffy',
 'Ampharos',
 'Bellossom',
 'Marill',
 'Azumarill',
 'Sudowoodo',
 'Politoed',
 'Hoppip',
 'Skiploom',
 'Jumpluff',
 'Aipom',
 'Sunkern',
 'Sunflora',
 'Yanma',
 'Wooper',
 'Quagsire',
 'Espeon',
 'Umbreon',
 'Murkrow',
 'Slowking',
 'Misdreavus',
 'Unown',
 'Wobbuffet',
 'Girafarig',
 'Pineco',
 'Forretress',
 'Dunsparce',
 'Gligar',
 'Steelix',
 'Snubbull',
 'Granbull',
 'Qwilfish',
 'Scizor',
 'Shuckle',
 'Heracross',
 'Sneasel',
 'Teddiursa',
 'Ursaring',
 'Slugma',
 'Magcargo',
 'Swinub',
 'Piloswine',
 'Corsola',
 'Remoraid',
 'Octillery',
 'Delibird',
 'Mantine',
 'Skarmory',
 'Houndour',
 'Houndoom',
 'Kingdra',
 'Phanpy',
 'Donphan',
 'Porygon2',
 'Stantler',
 'Smeargle',
 'Tyrogue',
 'Hitmontop',
 'Smoochum',
 'Elekid',
 'Magby',
 'Miltank',
 'Blissey',
 'Raikou',
 'Entei',
 'Suicune',
 'Larvitar',
 'Pupitar',
 'Tyranitar',
 'Lugia',
 'Ho-Oh',
 'Celebi',
 'Treecko',
 'Grovyle',
 'Sceptile',
 'Torchic',
 'Combusken',
 'Blaziken',
 'Mudkip',
 'Marshtomp',
 'Swampert',
 'Poochyena',
 'Mightyena',
 'Zigzagoon',
 'Linoone',
 'Wurmple',
 'Silcoon',
 'Beautifly',
 'Cascoon',
 'Dustox',
 'Lotad',
 'Lombre',
 'Ludicolo',
 'Seedot',
 'Nuzleaf',
 'Shiftry',
 'Taillow',
 'Swellow',
 'Wingull',
 'Pelipper',
 'Ralts',
 'Kirlia',
 'Gardevoir',
 'Surskit',
 'Masquerain',
 'Shroomish',
 'Breloom',
 'Slakoth',
 'Vigoroth',
 'Slaking',
 'Nincada',
 'Ninjask',
 'Shedinja',
 'Whismur',
 'Loudred',
 'Exploud',
 'Makuhita',
 'Hariyama',
 'Azurill',
 'Nosepass',
 'Skitty',
 'Delcatty',
 'Sableye',
 'Mawile',
 'Aron',
 'Lairon',
 'Aggron',
 'Meditite',
 'Medicham',
 'Electrike',
 'Manectric',
 'Plusle',
 'Minun',
 'Volbeat',
 'Illumise',
 'Roselia',
 'Gulpin',
 'Swalot',
 'Carvanha',
 'Sharpedo',
 'Wailmer',
 'Wailord',
 'Numel',
 'Camerupt',
 'Torkoal',
 'Spoink',
 'Grumpig',
 'Spinda',
 'Trapinch',
 'Vibrava',
 'Flygon',
 'Cacnea',
 'Cacturne',
 'Swablu',
 'Altaria',
 'Zangoose',
 'Seviper',
 'Lunatone',
 'Solrock',
 'Barboach',
 'Whiscash',
 'Corphish',
 'Crawdaunt',
 'Baltoy',
 'Claydol',
 'Lileep',
 'Cradily',
 'Anorith',
 'Armaldo',
 'Feebas',
 'Milotic',
 'Castform',
 'Kecleon',
 'Shuppet',
 'Banette',
 'Duskull',
 'Dusclops',
 'Tropius',
 'Chimecho',
 'Absol',
 'Wynaut',
 'Snorunt',
 'Glalie',
 'Spheal',
 'Sealeo',
 'Walrein',
 'Clamperl',
 'Huntail',
 'Gorebyss',
 'Relicanth',
 'Luvdisc',
 'Bagon',
 'Shelgon',
 'Salamence',
 'Beldum',
 'Metang',
 'Metagross',
 'Regirock',
 'Regice',
 'Registeel',
 'Latias',
 'Latios',
 'Kyogre',
 'Groudon',
 'Rayquaza',
 'Jirachi',
 'Deoxys',
 'Turtwig',
 'Grotle',
 'Torterra',
 'Chimchar',
 'Monferno',
 'Infernape',
 'Piplup',
 'Prinplup',
 'Empoleon',
 'Starly',
 'Staravia',
 'Staraptor',
 'Bidoof',
 'Bibarel',
 'Kricketot',
 'Kricketune',
 'Shinx',
 'Luxio',
 'Luxray',
 'Budew',
 'Roserade',
 'Cranidos',
 'Rampardos',
 'Shieldon',
 'Bastiodon',
 'Burmy',
 'Wormadam',
 'Mothim',
 'Combee',
 'Vespiquen',
 'Pachirisu',
 'Buizel',
 'Floatzel',
 'Cherubi',
 'Cherrim',
 'Shellos',
 'Gastrodon',
 'Ambipom',
 'Drifloon',
 'Drifblim',
 'Buneary',
 'Lopunny',
 'Mismagius',
 'Honchkrow',
 'Glameow',
 'Purugly',
 'Chingling',
 'Stunky',
 'Skuntank',
 'Bronzor',
 'Bronzong',
 'Bonsly',
 'Mime Jr.',
 'Happiny',
 'Chatot',
 'Spiritomb',
 'Gible',
 'Gabite',
 'Garchomp',
 'Munchlax',
 'Riolu',
 'Lucario',
 'Hippopotas',
 'Hippowdon',
 'Skorupi',
 'Drapion',
 'Croagunk',
 'Toxicroak',
 'Carnivine',
 'Finneon',
 'Lumineon',
 'Mantyke',
 'Snover',
 'Abomasnow',
 'Weavile',
 'Magnezone',
 'Lickilicky',
 'Rhyperior',
 'Tangrowth',
 'Electivire',
 'Magmortar',
 'Togekiss',
 'Yanmega',
 'Leafeon',
 'Glaceon',
 'Gliscor',
 'Mamoswine',
 'Porygon-Z',
 'Gallade',
 'Probopass',
 'Dusknoir',
 'Froslass',
 'Rotom',
 'Uxie',
 'Mesprit',
 'Azelf',
 'Dialga',
 'Palkia',
 'Heatran',
 'Regigigas',
 'Giratina',
 'Cresselia',
 'Phione',
 'Manaphy',
 'Darkrai',
 'Shaymin',
 'Arceus',
 'Victini',
 'Snivy',
 'Servine',
 'Serperior',
 'Tepig',
 'Pignite',
 'Emboar',
 'Oshawott',
 'Dewott',
 'Samurott',
 'Patrat',
 'Watchog',
 'Lillipup',
 'Herdier',
 'Stoutland',
 'Purrloin',
 'Liepard',
 'Pansage',
 'Simisage',
 'Pansear',
 'Simisear',
 'Panpour',
 'Simipour',
 'Munna',
 'Musharna',
 'Pidove',
 'Tranquill',
 'Unfezant',
 'Blitzle',
 'Zebstrika',
 'Roggenrola',
 'Boldore',
 'Gigalith',
 'Woobat',
 'Swoobat',
 'Drilbur',
 'Excadrill',
 'Audino',
 'Timburr',
 'Gurdurr',
 'Conkeldurr',
 'Tympole',
 'Palpitoad',
 'Seismitoad',
 'Throh',
 'Sawk',
 'Sewaddle',
 'Swadloon',
 'Leavanny',
 'Venipede',
 'Whirlipede',
 'Scolipede',
 'Cottonee',
 'Whimsicott',
 'Petilil',
 'Lilligant',
 'Basculin',
 'Sandile',
 'Krokorok',
 'Krookodile',
 'Darumaka',
 'Darmanitan',
 'Maractus',
 'Dwebble',
 'Crustle',
 'Scraggy',
 'Scrafty',
 'Sigilyph',
 'Yamask',
 'Cofagrigus',
 'Tirtouga',
 'Carracosta',
 'Archen',
 'Archeops',
 'Trubbish',
 'Garbodor',
 'Zorua',
 'Zoroark',
 'Minccino',
 'Cinccino',
 'Gothita',
 'Gothorita',
 'Gothitelle',
 'Solosis',
 'Duosion',
 'Reuniclus',
 'Ducklett',
 'Swanna',
 'Vanillite',
 'Vanillish',
 'Vanilluxe',
 'Deerling',
 'Sawsbuck',
 'Emolga',
 'Karrablast',
 'Escavalier',
 'Foongus',
 'Amoonguss',
 'Frillish',
 'Jellicent',
 'Alomomola',
 'Joltik',
 'Galvantula',
 'Ferroseed',
 'Ferrothorn',
 'Klink',
 'Klang',
 'Klinklang',
 'Tynamo',
 'Eelektrik',
 'Eelektross',
 'Elgyem',
 'Beheeyem',
 'Litwick',
 'Lampent',
 'Chandelure',
 'Axew',
 'Fraxure',
 'Haxorus',
 'Cubchoo',
 'Beartic',
 'Cryogonal',
 'Shelmet',
 'Accelgor',
 'Stunfisk',
 'Mienfoo',
 'Mienshao',
 'Druddigon',
 'Golett',
 'Golurk',
 'Pawniard',
 'Bisharp',
 'Bouffalant',
 'Rufflet',
 'Braviary',
 'Vullaby',
 'Mandibuzz',
 'Heatmor',
 'Durant',
 'Deino',
 'Zweilous',
 'Hydreigon',
 'Larvesta',
 'Volcarona',
 'Cobalion',
 'Terrakion',
 'Virizion',
 'Tornadus',
 'Thundurus',
 'Reshiram',
 'Zekrom',
 'Landorus',
 'Kyurem',
 'Keldeo',
 'Meloetta',
 'Genesect',
 'Chespin',
 'Quilladin',
 'Chesnaught',
 'Fennekin',
 'Braixen',
 'Delphox',
 'Froakie',
 'Frogadier',
 'Greninja',
 'Bunnelby',
 'Diggersby',
 'Fletchling',
 'Fletchinder',
 'Talonflame',
 'Scatterbug',
 'Spewpa',
 'Vivillon',
 'Litleo',
 'Pyroar',
 'Flabébé',
 'Floette',
 'Florges',
 'Skiddo',
 'Gogoat',
 'Pancham',
 'Pangoro',
 'Furfrou',
 'Espurr',
 'Meowstic',
 'Honedge',
 'Doublade',
 'Aegislash',
 'Spritzee',
 'Aromatisse',
 'Swirlix',
 'Slurpuff',
 'Inkay',
 'Malamar',
 'Binacle',
 'Barbaracle',
 'Skrelp',
 'Dragalge',
 'Clauncher',
 'Clawitzer',
 'Helioptile',
 'Heliolisk',
 'Tyrunt',
 'Tyrantrum',
 'Amaura',
 'Aurorus',
 'Sylveon',
 'Hawlucha',
 'Dedenne',
 'Carbink',
 'Goomy',
 'Sliggoo',
 'Goodra',
 'Klefki',
 'Phantump',
 'Trevenant',
 'Pumpkaboo',
 'Gourgeist',
 'Bergmite',
 'Avalugg',
 'Noibat',
 'Noivern',
 'Xerneas',
 'Yveltal',
 'Zygarde',
 'Diancie',
 'Hoopa',
 'Volcanion',
 'Rowlet',
 'Dartrix',
 'Decidueye',
 'Litten',
 'Torracat',
 'Incineroar',
 'Popplio',
 'Brionne',
 'Primarina',
 'Pikipek',
 'Trumbeak',
 'Toucannon',
 'Yungoos',
 'Gumshoos',
 'Grubbin',
 'Charjabug',
 'Vikavolt',
 'Crabrawler',
 'Crabominable',
 'Oricorio',
 'Cutiefly',
 'Ribombee',
 'Rockruff',
 'Lycanroc',
 'Wishiwashi',
 'Mareanie',
 'Toxapex',
 'Mudbray',
 'Mudsdale',
 'Dewpider',
 'Araquanid',
 'Fomantis',
 'Lurantis',
 'Morelull',
 'Shiinotic',
 'Salandit',
 'Salazzle',
 'Stufful',
 'Bewear',
 'Bounsweet',
 'Steenee',
 'Tsareena',
 'Comfey',
 'Oranguru',
 'Passimian',
 'Wimpod',
 'Golisopod',
 'Sandygast',
 'Palossand',
 'Pyukumuku',
 'Type: Null',
 'Silvally',
 'Minior',
 'Komala',
 'Turtonator',
 'Togedemaru',
 'Mimikyu',
 'Bruxish',
 'Drampa',
 'Dhelmise',
 'Jangmo-o',
 'Hakamo-o',
 'Kommo-o',
 'Tapu Koko',
 'Tapu Lele',
 'Tapu Bulu',
 'Tapu Fini',
 'Cosmog',
 'Cosmoem',
 'Solgaleo',
 'Lunala',
 'Nihilego',
 'Buzzwole',
 'Pheromosa',
 'Xurkitree',
 'Celesteela',
 'Kartana',
 'Guzzlord',
 'Necrozma',
 'Magearna',
 'Marshadow',
 'Poipole',
 'Naganadel',
 'Stakataka',
 'Blacephalon',
 'Zeraora',
 'Meltan',
 'Melmetal',
 'Grookey',
 'Thwackey',
 'Rillaboom',
 'Scorbunny',
 'Raboot',
 'Cinderace',
 'Sobble',
 'Drizzile',
 'Inteleon',
 'Skwovet',
 'Greedent',
 'Rookidee',
 'Corvisquire',
 'Corviknight',
 'Blipbug',
 'Dottler',
 'Orbeetle',
 'Nickit',
 'Thievul',
 'Gossifleur',
 'Eldegoss',
 'Wooloo',
 'Dubwool',
 'Chewtle',
 'Drednaw',
 'Yamper',
 'Boltund',
 'Rolycoly',
 'Carkol',
 'Coalossal',
 'Applin',
 'Flapple',
 'Appletun',
 'Silicobra',
 'Sandaconda',
 'Cramorant',
 'Arrokuda',
 'Barraskewda',
 'Toxel',
 'Toxtricity',
 'Sizzlipede',
 'Centiskorch',
 'Clobbopus',
 'Grapploct',
 'Sinistea',
 'Polteageist',
 'Hatenna',
 'Hattrem',
 'Hatterene',
 'Impidimp',
 'Morgrem',
 'Grimmsnarl',
 'Obstagoon',
 'Perrserker',
 'Cursola',
 'Sirfetch’d',
 'Mr. Rime',
 'Runerigus',
 'Milcery',
 'Alcremie',
 'Falinks',
 'Pincurchin',
 'Snom',
 'Frosmoth',
 'Stonjourner',
 'Eiscue',
 'Indeedee',
 'Morpeko',
 'Cufant',
 'Copperajah',
 'Dracozolt',
 'Arctozolt',
 'Dracovish',
 'Arctovish',
 'Duraludon',
 'Dreepy',
 'Drakloak',
 'Dragapult',
 'Zacian',
 'Zamazenta',
 'Eternatus',
 'Kubfu',
 'Urshifu',
 'Zarude',
 'Regieleki',
 'Regidrago',
 'Glastrier',
 'Spectrier',
 'Calyrex',
 'Wyrdeer',
 'Kleavor',
 'Ursaluna',
 'Basculegion',
 'Sneasler',
 'Overqwil',
 'Enamorus',
 'Sprigatito',
 'Floragato',
 'Meowscarada',
 'Fuecoco',
 'Crocalor',
 'Skeledirge',
 'Quaxly',
 'Quaxwell',
 'Quaquaval',
 'Lechonk',
 'Oinkologne',
 'Tarountula',
 'Spidops',
 'Nymble',
 'Lokix',
 'Pawmi',
 'Pawmo',
 'Pawmot',
 'Tandemaus',
 'Maushold',
 'Fidough',
 'Dachsbun',
 'Smoliv',
 'Dolliv',
 'Arboliva',
 'Squawkabilly',
 'Nacli',
 'Naclstack',
 'Garganacl',
 'Charcadet',
 'Armarouge',
 'Ceruledge',
 'Tadbulb',
 'Bellibolt',
 'Wattrel',
 'Kilowattrel',
 'Maschiff',
 'Mabosstiff',
 'Shroodle',
 'Grafaiai',
 'Bramblin',
 'Brambleghast',
 'Toedscool',
 'Toedscruel',
 'Klawf',
 'Capsakid',
 'Scovillain',
 'Rellor',
 'Rabsca',
 'Flittle',
 'Espathra',
 'Tinkatink',
 'Tinkatuff',
 'Tinkaton',
 'Wiglett',
 'Wugtrio',
 'Bombirdier',
 'Finizen',
 'Palafin',
 'Varoom',
 'Revavroom',
 'Cyclizar',
 'Orthworm',
 'Glimmet',
 'Glimmora',
 'Greavard',
 'Houndstone',
 'Flamigo',
 'Cetoddle',
 'Cetitan',
 'Veluza',
 'Dondozo',
 'Tatsugiri',
 'Annihilape',
 'Clodsire',
 'Farigiraf',
 'Dudunsparce',
 'Kingambit',
 'Great Tusk',
 'Scream Tail',
 'Brute Bonnet',
 'Flutter Mane',
 'Slither Wing',
 'Sandy Shocks',
 'Iron Treads',
 'Iron Bundle',
 'Iron Hands',
 'Iron Jugulis',
 'Iron Moth',
 'Iron Thorns',
 'Frigibax',
 'Arctibax',
 'Baxcalibur',
 'Gimmighoul',
 'Gholdengo',
 ...]

In [10]:
sorted(pokemon)

['Abomasnow',
 'Abra',
 'Absol',
 'Accelgor',
 'Aegislash',
 'Aerodactyl',
 'Aggron',
 'Aipom',
 'Alakazam',
 'Alcremie',
 'Alomomola',
 'Altaria',
 'Amaura',
 'Ambipom',
 'Amoonguss',
 'Ampharos',
 'Annihilape',
 'Anorith',
 'Appletun',
 'Applin',
 'Araquanid',
 'Arbok',
 'Arboliva',
 'Arcanine',
 'Arceus',
 'Archen',
 'Archeops',
 'Arctibax',
 'Arctovish',
 'Arctozolt',
 'Ariados',
 'Armaldo',
 'Armarouge',
 'Aromatisse',
 'Aron',
 'Arrokuda',
 'Articuno',
 'Audino',
 'Aurorus',
 'Avalugg',
 'Axew',
 'Azelf',
 'Azumarill',
 'Azurill',
 'Bagon',
 'Baltoy',
 'Banette',
 'Barbaracle',
 'Barboach',
 'Barraskewda',
 'Basculegion',
 'Basculin',
 'Bastiodon',
 'Baxcalibur',
 'Bayleef',
 'Beartic',
 'Beautifly',
 'Beedrill',
 'Beheeyem',
 'Beldum',
 'Bellibolt',
 'Bellossom',
 'Bellsprout',
 'Bergmite',
 'Bewear',
 'Bibarel',
 'Bidoof',
 'Binacle',
 'Bisharp',
 'Blacephalon',
 'Blastoise',
 'Blaziken',
 'Blipbug',
 'Blissey',
 'Blitzle',
 'Boldore',
 'Boltund',
 'Bombirdier',
 'Bonsly',
 'Bouffalant',
 'Bounsweet',
 'Braixen',
 'Brambleghast',
 'Bramblin',
 'Braviary',
 'Breloom',
 'Brionne',
 'Bronzong',
 'Bronzor',
 'Brute Bonnet',
 'Bruxish',
 'Budew',
 'Buizel',
 'Bulbasaur',
 'Buneary',
 'Bunnelby',
 'Burmy',
 'Butterfree',
 'Buzzwole',
 'Cacnea',
 'Cacturne',
 'Calyrex',
 'Camerupt',
 'Capsakid',
 'Carbink',
 'Carkol',
 'Carnivine',
 'Carracosta',
 'Carvanha',
 'Cascoon',
 'Castform',
 'Caterpie',
 'Celebi',
 'Celesteela',
 'Centiskorch',
 'Ceruledge',
 'Cetitan',
 'Cetoddle',
 'Chandelure',
 'Chansey',
 'Charcadet',
 'Charizard',
 'Charjabug',
 'Charmander',
 'Charmeleon',
 'Chatot',
 'Cherrim',
 'Cherubi',
 'Chesnaught',
 'Chespin',
 'Chewtle',
 'Chi-Yu',
 'Chien-Pao',
 'Chikorita',
 'Chimchar',
 'Chimecho',
 'Chinchou',
 'Chingling',
 'Cinccino',
 'Cinderace',
 'Clamperl',
 'Clauncher',
 'Clawitzer',
 'Claydol',
 'Clefable',
 'Clefairy',
 'Cleffa',
 'Clobbopus',
 'Clodsire',
 'Cloyster',
 'Coalossal',
 'Cobalion',
 'Cofagrigus',
 'Combee',
 'Combusken',
 'Comfey',
 'Conkeldurr',
 'Copperajah',
 'Corphish',
 'Corsola',
 'Corviknight',
 'Corvisquire',
 'Cosmoem',
 'Cosmog',
 'Cottonee',
 'Crabominable',
 'Crabrawler',
 'Cradily',
 'Cramorant',
 'Cranidos',
 'Crawdaunt',
 'Cresselia',
 'Croagunk',
 'Crobat',
 'Crocalor',
 'Croconaw',
 'Crustle',
 'Cryogonal',
 'Cubchoo',
 'Cubone',
 'Cufant',
 'Cursola',
 'Cutiefly',
 'Cyclizar',
 'Cyndaquil',
 'Dachsbun',
 'Darkrai',
 'Darmanitan',
 'Dartrix',
 'Darumaka',
 'Decidueye',
 'Dedenne',
 'Deerling',
 'Deino',
 'Delcatty',
 'Delibird',
 'Delphox',
 'Deoxys',
 'Dewgong',
 'Dewott',
 'Dewpider',
 'Dhelmise',
 'Dialga',
 'Diancie',
 'Diggersby',
 'Diglett',
 'Ditto',
 'Dodrio',
 'Doduo',
 'Dolliv',
 'Dondozo',
 'Donphan',
 'Dottler',
 'Doublade',
 'Dracovish',
 'Dracozolt',
 'Dragalge',
 'Dragapult',
 'Dragonair',
 'Dragonite',
 'Drakloak',
 'Drampa',
 'Drapion',
 'Dratini',
 'Drednaw',
 'Dreepy',
 'Drifblim',
 'Drifloon',
 'Drilbur',
 'Drizzile',
 'Drowzee',
 'Druddigon',
 'Dubwool',
 'Ducklett',
 'Dudunsparce',
 'Dugtrio',
 'Dunsparce',
 'Duosion',
 'Duraludon',
 'Durant',
 'Dusclops',
 'Dusknoir',
 'Duskull',
 'Dustox',
 'Dwebble',
 'Eelektrik',
 'Eelektross',
 'Eevee',
 'Eiscue',
 'Ekans',
 'Eldegoss',
 'Electabuzz',
 'Electivire',
 'Electrike',
 'Electrode',
 'Elekid',
 'Elgyem',
 'Emboar',
 'Emolga',
 'Empoleon',
 'Enamorus',
 'Entei',
 'Escavalier',
 'Espathra',
 'Espeon',
 'Espurr',
 'Eternatus',
 'Excadrill',
 'Exeggcute',
 'Exeggutor',
 'Exploud',
 'Falinks',
 'Farfetch’d',
 'Farigiraf',
 'Fearow',
 'Feebas',
 'Fennekin',
 'Feraligatr',
 'Ferroseed',
 'Ferrothorn',
 'Fidough',
 'Finizen',
 'Finneon',
 'Flaaffy',
 'Flabébé',
 'Flamigo',
 'Flapple',
 'Flareon',
 'Fletchinder',
 'Fletchling',
 'Flittle',
 'Floatzel',
 'Floette',
 'Floragato',
 'Florges',
 'Flutter Mane',
 'Flygon',
 'Fomantis',
 'Foongus',
 'Forretress',
 'Fraxure',
 'Frigibax',
 'Frillish',
 'Froakie',
 'Frogadier',
 'Froslass',
 'Frosmoth',
 'Fuecoco',
 'Furfrou',
 'Furret',
 'Gabite',
 'Gallade',
 'Galvantula',
 'Garbodor',
 'Garchomp',
 'Gardevoir',
 'Garganacl',
 'Gastly',
 'Gastrodon',
 'Genesect',
 'Gengar',
 'Geodude',
 'Gholdengo',
 'Gible',
 'Gigalith',
 'Gimmighoul',
 'Girafarig',
 'Giratina',
 'Glaceon',
 'Glalie',
 'Glameow',
 'Glastrier',
 'Gligar',
 'Glimmet',
 'Glimmora',
 'Gliscor',
 'Gloom',
 'Gogoat',
 'Golbat',
 'Goldeen',
 'Golduck',
 'Golem',
 'Golett',
 'Golisopod',
 'Golurk',
 'Goodra',
 'Goomy',
 'Gorebyss',
 'Gossifleur',
 'Gothita',
 'Gothitelle',
 'Gothorita',
 'Gourgeist',
 'Grafaiai',
 'Granbull',
 'Grapploct',
 'Graveler',
 'Great Tusk',
 'Greavard',
 'Greedent',
 'Greninja',
 'Grimer',
 'Grimmsnarl',
 'Grookey',
 'Grotle',
 'Groudon',
 'Grovyle',
 'Growlithe',
 'Grubbin',
 'Grumpig',
 'Gulpin',
 'Gumshoos',
 'Gurdurr',
 'Guzzlord',
 'Gyarados',
 'Hakamo-o',
 'Happiny',
 'Hariyama',
 'Hatenna',
 'Hatterene',
 'Hattrem',
 'Haunter',
 'Hawlucha',
 'Haxorus',
 'Heatmor',
 'Heatran',
 'Heliolisk',
 'Helioptile',
 'Heracross',
 'Herdier',
 'Hippopotas',
 'Hippowdon',
 'Hitmonchan',
 'Hitmonlee',
 'Hitmontop',
 'Ho-Oh',
 'Honchkrow',
 'Honedge',
 'Hoopa',
 'Hoothoot',
 'Hoppip',
 'Horsea',
 'Houndoom',
 'Houndour',
 'Houndstone',
 'Huntail',
 'Hydreigon',
 'Hypno',
 'Igglybuff',
 'Illumise',
 'Impidimp',
 'Incineroar',
 'Indeedee',
 'Infernape',
 'Inkay',
 'Inteleon',
 'Iron Bundle',
 'Iron Hands',
 'Iron Jugulis',
 'Iron Leaves',
 'Iron Moth',
 'Iron Thorns',
 'Iron Treads',
 'Iron Valiant',
 'Ivysaur',
 'Jangmo-o',
 'Jellicent',
 'Jigglypuff',
 'Jirachi',
 'Jolteon',
 'Joltik',
 'Jumpluff',
 'Jynx',
 'Kabuto',
 'Kabutops',
 'Kadabra',
 'Kakuna',
 'Kangaskhan',
 'Karrablast',
 'Kartana',
 'Kecleon',
 'Keldeo',
 'Kilowattrel',
 'Kingambit',
 'Kingdra',
 'Kingler',
 'Kirlia',
 'Klang',
 'Klawf',
 'Kleavor',
 'Klefki',
 'Klink',
 'Klinklang',
 'Koffing',
 'Komala',
 'Kommo-o',
 'Koraidon',
 'Krabby',
 'Kricketot',
 'Kricketune',
 'Krokorok',
 'Krookodile',
 'Kubfu',
 'Kyogre',
 'Kyurem',
 'Lairon',
 'Lampent',
 'Landorus',
 'Lanturn',
 'Lapras',
 'Larvesta',
 'Larvitar',
 'Latias',
 'Latios',
 'Leafeon',
 'Leavanny',
 'Lechonk',
 'Ledian',
 'Ledyba',
 'Lickilicky',
 'Lickitung',
 'Liepard',
 'Lileep',
 'Lilligant',
 'Lillipup',
 'Linoone',
 'Litleo',
 'Litten',
 'Litwick',
 'Lokix',
 'Lombre',
 'Lopunny',
 'Lotad',
 'Loudred',
 'Lucario',
 'Ludicolo',
 'Lugia',
 'Lumineon',
 'Lunala',
 'Lunatone',
 'Lurantis',
 'Luvdisc',
 'Luxio',
 'Luxray',
 'Lycanroc',
 'Mabosstiff',
 'Machamp',
 'Machoke',
 'Machop',
 'Magby',
 'Magcargo',
 'Magearna',
 'Magikarp',
 'Magmar',
 'Magmortar',
 'Magnemite',
 'Magneton',
 'Magnezone',
 'Makuhita',
 'Malamar',
 'Mamoswine',
 'Manaphy',
 'Mandibuzz',
 'Manectric',
 'Mankey',
 'Mantine',
 'Mantyke',
 'Maractus',
 'Mareanie',
 'Mareep',
 'Marill',
 'Marowak',
 'Marshadow',
 'Marshtomp',
 'Maschiff',
 'Masquerain',
 'Maushold',
 'Mawile',
 'Medicham',
 'Meditite',
 'Meganium',
 'Melmetal',
 'Meloetta',
 'Meltan',
 'Meowscarada',
 'Meowstic',
 'Meowth',
 'Mesprit',
 'Metagross',
 'Metang',
 'Metapod',
 'Mew',
 'Mewtwo',
 'Mienfoo',
 'Mienshao',
 'Mightyena',
 'Milcery',
 'Milotic',
 'Miltank',
 'Mime Jr.',
 'Mimikyu',
 'Minccino',
 'Minior',
 'Minun',
 'Miraidon',
 'Misdreavus',
 'Mismagius',
 'Moltres',
 'Monferno',
 'Morelull',
 'Morgrem',
 'Morpeko',
 'Mothim',
 'Mr. Mime',
 'Mr. Rime',
 'Mudbray',
 'Mudkip',
 'Mudsdale',
 'Muk',
 'Munchlax',
 'Munna',
 'Murkrow',
 'Musharna',
 'Nacli',
 'Naclstack',
 'Naganadel',
 'Natu',
 'Necrozma',
 'Nickit',
 'Nidoking',
 'Nidoqueen',
 'Nidoran♀',
 'Nidoran♂',
 'Nidorina',
 'Nidorino',
 'Nihilego',
 'Nincada',
 'Ninetales',
 'Ninjask',
 'Noctowl',
 'Noibat',
 'Noivern',
 'Nosepass',
 'Numel',
 'Nuzleaf',
 'Nymble',
 'Obstagoon',
 'Octillery',
 'Oddish',
 'Oinkologne',
 'Omanyte',
 'Omastar',
 'Onix',
 'Oranguru',
 'Orbeetle',
 'Oricorio',
 'Orthworm',
 'Oshawott',
 'Overqwil',
 'Pachirisu',
 'Palafin',
 'Palkia',
 'Palossand',
 'Palpitoad',
 'Pancham',
 'Pangoro',
 'Panpour',
 'Pansage',
 'Pansear',
 'Paras',
 'Parasect',
 'Passimian',
 'Patrat',
 'Pawmi',
 'Pawmo',
 'Pawmot',
 'Pawniard',
 'Pelipper',
 'Perrserker',
 'Persian',
 'Petilil',
 'Phanpy',
 'Phantump',
 'Pheromosa',
 'Phione',
 'Pichu',
 'Pidgeot',
 'Pidgeotto',
 'Pidgey',
 'Pidove',
 'Pignite',
 'Pikachu',
 'Pikipek',
 'Piloswine',
 'Pincurchin',
 'Pineco',
 'Pinsir',
 'Piplup',
 'Plusle',
 'Poipole',
 'Politoed',
 'Poliwag',
 'Poliwhirl',
 'Poliwrath',
 'Polteageist',
 'Ponyta',
 'Poochyena',
 'Popplio',
 'Porygon',
 'Porygon-Z',
 'Porygon2',
 'Primarina',
 'Primeape',
 'Prinplup',
 'Probopass',
 'Psyduck',
 'Pumpkaboo',
 'Pupitar',
 'Purrloin',
 'Purugly',
 'Pyroar',
 'Pyukumuku',
 'Quagsire',
 'Quaquaval',
 'Quaxly',
 'Quaxwell',
 'Quilava',
 'Quilladin',
 'Qwilfish',
 'Raboot',
 'Rabsca',
 'Raichu',
 'Raikou',
 'Ralts',
 'Rampardos',
 'Rapidash',
 'Raticate',
 'Rattata',
 'Rayquaza',
 'Regice',
 'Regidrago',
 'Regieleki',
 'Regigigas',
 'Regirock',
 'Registeel',
 'Relicanth',
 'Rellor',
 'Remoraid',
 'Reshiram',
 'Reuniclus',
 'Revavroom',
 'Rhydon',
 'Rhyhorn',
 'Rhyperior',
 'Ribombee',
 'Rillaboom',
 'Riolu',
 'Roaring Moon',
 'Rockruff',
 'Roggenrola',
 'Rolycoly',
 'Rookidee',
 'Roselia',
 'Roserade',
 'Rotom',
 'Rowlet',
 'Rufflet',
 'Runerigus',
 'Sableye',
 'Salamence',
 'Salandit',
 'Salazzle',
 'Samurott',
 'Sandaconda',
 'Sandile',
 'Sandshrew',
 'Sandslash',
 'Sandy Shocks',
 'Sandygast',
 'Sawk',
 'Sawsbuck',
 'Scatterbug',
 'Sceptile',
 'Scizor',
 'Scolipede',
 'Scorbunny',
 'Scovillain',
 'Scrafty',
 'Scraggy',
 'Scream Tail',
 'Scyther',
 'Seadra',
 'Seaking',
 'Sealeo',
 'Seedot',
 'Seel',
 'Seismitoad',
 'Sentret',
 'Serperior',
 'Servine',
 'Seviper',
 'Sewaddle',
 'Sharpedo',
 'Shaymin',
 'Shedinja',
 'Shelgon',
 'Shellder',
 'Shellos',
 'Shelmet',
 'Shieldon',
 'Shiftry',
 'Shiinotic',
 'Shinx',
 'Shroodle',
 'Shroomish',
 'Shuckle',
 'Shuppet',
 'Sigilyph',
 'Silcoon',
 'Silicobra',
 'Silvally',
 'Simipour',
 'Simisage',
 'Simisear',
 'Sinistea',
 'Sirfetch’d',
 'Sizzlipede',
 'Skarmory',
 'Skeledirge',
 'Skiddo',
 'Skiploom',
 'Skitty',
 'Skorupi',
 'Skrelp',
 'Skuntank',
 'Skwovet',
 'Slaking',
 'Slakoth',
 'Sliggoo',
 'Slither Wing',
 'Slowbro',
 'Slowking',
 'Slowpoke',
 'Slugma',
 'Slurpuff',
 'Smeargle',
 'Smoliv',
 'Smoochum',
 'Sneasel',
 'Sneasler',
 'Snivy',
 'Snom',
 'Snorlax',
 'Snorunt',
 'Snover',
 'Snubbull',
 'Sobble',
 'Solgaleo',
 'Solosis',
 'Solrock',
 'Spearow',
 'Spectrier',
 'Spewpa',
 'Spheal',
 'Spidops',
 'Spinarak',
 'Spinda',
 'Spiritomb',
 'Spoink',
 'Sprigatito',
 'Spritzee',
 'Squawkabilly',
 'Squirtle',
 'Stakataka',
 'Stantler',
 'Staraptor',
 'Staravia',
 'Starly',
 'Starmie',
 'Staryu',
 'Steelix',
 'Steenee',
 'Stonjourner',
 'Stoutland',
 'Stufful',
 'Stunfisk',
 'Stunky',
 'Sudowoodo',
 'Suicune',
 'Sunflora',
 'Sunkern',
 'Surskit',
 'Swablu',
 'Swadloon',
 'Swalot',
 'Swampert',
 'Swanna',
 'Swellow',
 'Swinub',
 'Swirlix',
 'Swoobat',
 'Sylveon',
 'Tadbulb',
 'Taillow',
 'Talonflame',
 'Tandemaus',
 'Tangela',
 'Tangrowth',
 'Tapu Bulu',
 'Tapu Fini',
 'Tapu Koko',
 'Tapu Lele',
 'Tarountula',
 'Tatsugiri',
 'Tauros',
 'Teddiursa',
 'Tentacool',
 'Tentacruel',
 'Tepig',
 'Terrakion',
 'Thievul',
 'Throh',
 'Thundurus',
 'Thwackey',
 'Timburr',
 'Ting-Lu',
 'Tinkatink',
 'Tinkaton',
 'Tinkatuff',
 'Tirtouga',
 'Toedscool',
 'Toedscruel',
 'Togedemaru',
 'Togekiss',
 'Togepi',
 'Togetic',
 'Torchic',
 'Torkoal',
 'Tornadus',
 'Torracat',
 'Torterra',
 'Totodile',
 'Toucannon',
 'Toxapex',
 'Toxel',
 'Toxicroak',
 'Toxtricity',
 'Tranquill',
 'Trapinch',
 'Treecko',
 'Trevenant',
 'Tropius',
 'Trubbish',
 'Trumbeak',
 'Tsareena',
 'Turtonator',
 'Turtwig',
 'Tympole',
 'Tynamo',
 'Type: Null',
 'Typhlosion',
 'Tyranitar',
 'Tyrantrum',
 'Tyrogue',
 'Tyrunt',
 'Umbreon',
 'Unfezant',
 'Unown',
 'Ursaluna',
 'Ursaring',
 'Urshifu',
 'Uxie',
 'Vanillish',
 'Vanillite',
 'Vanilluxe',
 'Vaporeon',
 'Varoom',
 'Veluza',
 'Venipede',
 'Venomoth',
 'Venonat',
 'Venusaur',
 'Vespiquen',
 'Vibrava',
 'Victini',
 'Victreebel',
 'Vigoroth',
 'Vikavolt',
 'Vileplume',
 'Virizion',
 'Vivillon',
 'Volbeat',
 'Volcanion',
 'Volcarona',
 'Voltorb',
 'Vullaby',
 'Vulpix',
 'Wailmer',
 'Wailord',
 'Walking Wake',
 'Walrein',
 'Wartortle',
 'Watchog',
 'Wattrel',
 'Weavile',
 'Weedle',
 'Weepinbell',
 'Weezing',
 'Whimsicott',
 'Whirlipede',
 'Whiscash',
 'Whismur',
 'Wigglytuff',
 'Wiglett',
 'Wimpod',
 'Wingull',
 'Wishiwashi',
 'Wo-Chien',
 'Wobbuffet',
 'Woobat',
 'Wooloo',
 'Wooper',
 'Wormadam',
 'Wugtrio',
 'Wurmple',
 'Wynaut',
 'Wyrdeer',
 'Xatu',
 'Xerneas',
 'Xurkitree',
 'Yamask',
 'Yamper',
 'Yanma',
 'Yanmega',
 'Yungoos',
 'Yveltal',
 'Zacian',
 'Zamazenta',
 'Zangoose',
 'Zapdos',
 ...]

In [11]:
min(pokemon)

'Abomasnow'

In [12]:
max(pokemon)

'Zygarde'

In [13]:
pokemon.shape

(1010,)

In [16]:
pokemon.head(25)

0      Bulbasaur
1        Ivysaur
2       Venusaur
3     Charmander
4     Charmeleon
5      Charizard
6       Squirtle
7      Wartortle
8      Blastoise
9       Caterpie
10       Metapod
11    Butterfree
12        Weedle
13        Kakuna
14      Beedrill
15        Pidgey
16     Pidgeotto
17       Pidgeot
18       Rattata
19      Raticate
20       Spearow
21        Fearow
22         Ekans
23         Arbok
24       Pikachu
Name: Name, dtype: object

In [17]:
pokemon.tail(25)

985     Brute Bonnet
986     Flutter Mane
987     Slither Wing
988     Sandy Shocks
989      Iron Treads
990      Iron Bundle
991       Iron Hands
992     Iron Jugulis
993        Iron Moth
994      Iron Thorns
995         Frigibax
996         Arctibax
997       Baxcalibur
998       Gimmighoul
999        Gholdengo
1000        Wo-Chien
1001       Chien-Pao
1002         Ting-Lu
1003          Chi-Yu
1004    Roaring Moon
1005    Iron Valiant
1006        Koraidon
1007        Miraidon
1008    Walking Wake
1009     Iron Leaves
Name: Name, dtype: object